### ISSUE TITLE
Option to disable PNG processing

### ISSUE THREAD

**Issue by 1024mb** [devedse/DeveImageOptimizerWPF#13]
Seeing how much time PNG optimization takes could you add an option to skip PNG files?
Another option to only process PNG files would be great too so we can leave the tool running through the night or while we are away.

**Comment by devedse** [comment]
Might be a good idea yeah. I might implement that in the future :).

**Comment by devedse** [comment]
I've just implemented this feature. Once this build completes it should be on chocolatey soon:
https://github.com/devedse/DeveImageOptimizerWPF/actions/runs/3975890309

**Comment by 1024mb** [comment]
thank you! Working great.
