### ISSUE TITLE
Enhancement: Add setting to sort from smallest image to largest image (and vice versa)

### ISSUE THREAD

**Issue by exurd** [devedse/DeveImageOptimizerWPF#6]
This will allow the smaller files to be compressed first and the largest ones to be compressed last, making the process feel faster.

**Comment by devedse** [comment]
Wow I never saw this issue, I'm sorry. I'll try to reply tomorrow.

**Comment by devedse** [comment]
Ok here I am, speaking from the future. (Relatively speaking)

The issue with this enhancement request is that the way the tool works is that it loops over all files and immediately starts processing them. If I would want to sort them by size I'd first have to loop over all files in the specified directory, then sort them, and then start processing. I could theoretically go by size per directory but yeah I personally prefer doing it by name (the way it is now).
