### ISSUE TITLE
Enhancement: Keep settings of exclusions and inclusions of plugins

### ISSUE THREAD

**Issue by exurd** [devedse/DeveImageOptimizerWPF#7]
I wanted to speed up the process for optimization (ECT just takes too long). So, I added it to the plugin exclusion mask in the settings.
For some reason, the program replaces those settings, meaning the plugin I wanted to disable becomes enabled again. I had to delete ECT.exe from the plugins folder. I'd rather not do that. The program should keep the settings of what I do and don't want to run.

**Comment by devedse** [comment]
Hey @exurd , today I've been working quite a bit on my Image Optimizer. I've added some features where you can actually configure the desired image optimization level. This will make the optimizer quite a bit faster. (Which hopefully means that we don't have to exclude ECT. Basically ECT is (by quite a margin) the best optimization tool included, so I'd rather not exclude it).

Incase you want to really get the limit of optimization you should select the Placebo option. It's a bit better then Maximum now. (Maximum being the limit of FileOptimizerFull).

The latest version can be found in the releases here: https://github.com/devedse/DeveImageOptimizerWPF/releases

I'm also submitting it to chocolatey, hopefully that works now, if not, I'll check it out tomorrow.

**Comment by devedse** [comment]
Chocolatey is also updated now. Please let me know if this fix will actually resolve your issue :).
