### ISSUE TITLE
Keep original modified and accessed timestamps

### ISSUE THREAD

**Issue by 1024mb** [devedse/DeveImageOptimizerWPF#8]
When processing files only the creation date is keept, please make it so all the three timestamps are.
Afaik ECT has the command `-keep` to do this.

**Comment by devedse** [comment]
Hmm I'd have to see how that works with all tools. The reason why I did this now was to be sure to have dropbox / backup programs sync the files once they get optimized.

**Comment by 1024mb** [comment]
It could be an optional switch so people that need it enable it. Thanks for looking at this.

**Comment by devedse** [comment]
Yeah I'll probably implement that sometime. Just a bit busy now, but it'll require me to pass the flag to all optimizers to ensure none of them removes this metadata.

Just some questions for my own interest:
1. How did you find my image optimizer?
2. For what are you using the application?
3. Any other comments / things?

**Comment by 1024mb** [comment]
>     1. How did you find my image optimizer?

I was looking for an alternative to FileOptimizer and was interested mainly in images and found yours which also has verification so it was a great alternative.


>     2. For what are you using the application?

I have a lot of images from data hoarding lots of stuff over the years and in order to save space I perform the optimizations.

>     3. Any other comments / things?

So far nothing else to add, my only issue is the one posted here as I like preserving all the original metadata.

Thanks for your work.

**Comment by Werve** [comment]
With this tool https://www.softwareok.com/?seite=Microsoft/NewFileTimes its possible to re-apply the previous timestamps
so based on the same logic should be implemented after a file optimization instead of check if some optimizers changed the metadata.

**Comment by devedse** [comment]
I could probably do the same with C# and re-apply the file permissions too. I just haven't really found the motivation to implement this feature yet 😿 . It might take a bit but I'll get back to this :).

**Comment by devedse** [comment]
@1024mb @Werve , just released a new version which includes a new checkbox to keep the file attributes. This should fix this issue 😄

**Comment by 1024mb** [comment]
I was checking the issue just a few hours ago. Thanks, I'll try it.

**Comment by devedse** [comment]
Cool, let me know if it works.

**Comment by 1024mb** [comment]
It's working great, dates remain unchanged now.

**Comment by devedse** [comment]
I just included log window inside the tool, rather then opening a separate window. If you have some time to test it and let me know any issues it would be nice :).
